-- MySQL Script generated by MySQL Workbench
-- Sun Nov 10 19:53:03 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema database_chodoido_ute
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema database_chodoido_ute
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database_chodoido_ute` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `database_chodoido_ute` ;

-- -----------------------------------------------------
-- Table `database_chodoido_ute`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_chodoido_ute`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `count_post` BIGINT NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `facebook` VARCHAR(255) NULL DEFAULT NULL,
  `gender` BIT(1) NULL DEFAULT NULL,
  `img_url` VARCHAR(255) NULL DEFAULT NULL,
  `local` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `nick_name` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `point` BIGINT NULL DEFAULT NULL,
  `product_lost` BIGINT NULL DEFAULT NULL,
  `product_success` BIGINT NULL DEFAULT NULL,
  `role` ENUM('ADMIN', 'USER') NULL DEFAULT NULL,
  `zalo` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `database_chodoido_ute`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_chodoido_ute`.`category` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `database_chodoido_ute`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_chodoido_ute`.`product` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `count` BIGINT NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `is_new` BIT(1) NOT NULL,
  `post_product_status` ENUM('CHO_DUYET', 'DA_AN', 'DA_BAN', 'DA_DUYET', 'DA_TUCHOI') NULL DEFAULT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  `time_post` DATETIME(6) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `id_category` BIGINT NULL DEFAULT NULL,
  `id_user` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK5cxv31vuhc7v32omftlxa8k3c` (`id_category` ASC) VISIBLE,
  INDEX `FKid3isj76xjkdr11j0kt10c4l7` (`id_user` ASC) VISIBLE,
  CONSTRAINT `FK5cxv31vuhc7v32omftlxa8k3c`
    FOREIGN KEY (`id_category`)
    REFERENCES `database_chodoido_ute`.`category` (`id`),
  CONSTRAINT `FKid3isj76xjkdr11j0kt10c4l7`
    FOREIGN KEY (`id_user`)
    REFERENCES `database_chodoido_ute`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `database_chodoido_ute`.`buy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_chodoido_ute`.`buy` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `count` BIGINT NULL DEFAULT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  `status` ENUM('CHO_XAC_NHAN', 'DANG_GIAO_DICH', 'THANH_CONG', 'THAT_BAI') NULL DEFAULT NULL,
  `time_buy` DATE NULL DEFAULT NULL,
  `id_product` BIGINT NULL DEFAULT NULL,
  `id_user_buy` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKiijmrt70f2gl5radv8toqvq6a` (`id_product` ASC) VISIBLE,
  INDEX `FKgg9e1g4tvdns5wm5sravrgy1q` (`id_user_buy` ASC) VISIBLE,
  CONSTRAINT `FKgg9e1g4tvdns5wm5sravrgy1q`
    FOREIGN KEY (`id_user_buy`)
    REFERENCES `database_chodoido_ute`.`user` (`id`),
  CONSTRAINT `FKiijmrt70f2gl5radv8toqvq6a`
    FOREIGN KEY (`id_product`)
    REFERENCES `database_chodoido_ute`.`product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `database_chodoido_ute`.`follower`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_chodoido_ute`.`follower` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `id_user` BIGINT NULL DEFAULT NULL,
  `id_user_follower` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKevqabq4adwsupvfqyrtiw4hko` (`id_user` ASC) VISIBLE,
  INDEX `FKbbef37d6xm2qhkuhk8hhgp20n` (`id_user_follower` ASC) VISIBLE,
  CONSTRAINT `FKbbef37d6xm2qhkuhk8hhgp20n`
    FOREIGN KEY (`id_user_follower`)
    REFERENCES `database_chodoido_ute`.`user` (`id`),
  CONSTRAINT `FKevqabq4adwsupvfqyrtiw4hko`
    FOREIGN KEY (`id_user`)
    REFERENCES `database_chodoido_ute`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `database_chodoido_ute`.`mission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_chodoido_ute`.`mission` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `is_mission_default` BIT(1) NULL DEFAULT NULL,
  `mission_type` ENUM('NAM', 'NGAY', 'THANG', 'TUYCHON') NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `point` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `database_chodoido_ute`.`mission_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_chodoido_ute`.`mission_details` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `date_checked` DATE NULL DEFAULT NULL,
  `mission_id` BIGINT NULL DEFAULT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKhsgs2e18silhm9resfa0td976` (`mission_id` ASC) VISIBLE,
  INDEX `FK6drrpwswmmpd4aucyi331wjg9` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK6drrpwswmmpd4aucyi331wjg9`
    FOREIGN KEY (`user_id`)
    REFERENCES `database_chodoido_ute`.`user` (`id`),
  CONSTRAINT `FKhsgs2e18silhm9resfa0td976`
    FOREIGN KEY (`mission_id`)
    REFERENCES `database_chodoido_ute`.`mission` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `database_chodoido_ute`.`product_img`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_chodoido_ute`.`product_img` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `url_img` VARCHAR(255) NULL DEFAULT NULL,
  `id_product` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK8ftr7ehor4vnc9tp0onlmucga` (`id_product` ASC) VISIBLE,
  CONSTRAINT `FK8ftr7ehor4vnc9tp0onlmucga`
    FOREIGN KEY (`id_product`)
    REFERENCES `database_chodoido_ute`.`product` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `database_chodoido_ute`.`product_video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_chodoido_ute`.`product_video` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `video_url` VARCHAR(255) NULL DEFAULT NULL,
  `id_product` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKm3pdx7oy4wyxerk6jk2qriuhh` (`id_product` ASC) VISIBLE,
  CONSTRAINT `FKm3pdx7oy4wyxerk6jk2qriuhh`
    FOREIGN KEY (`id_product`)
    REFERENCES `database_chodoido_ute`.`product` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `database_chodoido_ute`.`service_package`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_chodoido_ute`.`service_package` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `count_post` BIGINT NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `point` BIGINT NULL DEFAULT NULL,
  `time` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `database_chodoido_ute`.`service_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_chodoido_ute`.`service_details` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `expiration` DATETIME(6) NULL DEFAULT NULL,
  `service_package_id` BIGINT NULL DEFAULT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKr9hapwhbj9xgkglmti49n6t2g` (`service_package_id` ASC) VISIBLE,
  INDEX `FKprdq2a9h8sh419s1sq9i0mxbn` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKprdq2a9h8sh419s1sq9i0mxbn`
    FOREIGN KEY (`user_id`)
    REFERENCES `database_chodoido_ute`.`user` (`id`),
  CONSTRAINT `FKr9hapwhbj9xgkglmti49n6t2g`
    FOREIGN KEY (`service_package_id`)
    REFERENCES `database_chodoido_ute`.`service_package` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
