
server:
  port: 4141


spring:
    datasource:
      url: ${DB_CONNECTION_STRING:jdbc:mysql://localhost:3306/database_chodoido_ute?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect

    servlet:
      multipart:
        max-request-size: 50MB
        max-file-size: 50MB
        enabled: true

    data:
      redis:
        port: 6379
        host: localhost

    mail:
      host: smtp.gmail.com
      port: 587
      username: ${EMAIL_KEY:""}
      password: ${EMAIL_PASS_KEY:""}
      protocol: smtp
      properties.mail.smtp.auth: true
      properties.mail.smtp.starttls.enable: true
      properties.mail.debug: true


aws:
  s3:
    access_Key: ${S3_ACCESS_KEY:""}
    secret_Key: ${S3_SECRET_KEY:""}

jwt:
  token:
    secret_Key: ${JWT_SECRET_KEY}
    expiration: 86400000
    expiration_refresh: 172800000


